name: date_format_example
description: Script for printing out date formats
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  intl: ^0.18.1

dev_dependencies:
  very_good_analysis: ^5.1.0

executables:
  date_format_example:
